# Site
title: r53-ddns
description: r53-ddns Amazon Route 53 DDNS

# Using Midnight theme: https://github.com/pages-themes/midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

google_analytics: G-QH0C0YJHW6
